### ISSUE TITLE
Inquiry about Serialization and Deserialization of the "data" Variable in plonky2-ecdsa

### ISSUE THREAD

**Issue by Hodgeson** [mir-protocol/plonky2-ecdsa#6]
Hi there,

I hope this message finds you well. I have a question regarding the serialization and deserialization process, specifically with respect to the "data" variable.

I'm focusing on the code snippet in the following link:
https://github.com/0xPolygonZero/plonky2-ecdsa/blob/bdb6504bca250db1548cdcce2407d4e334990c33/src/gadgets/ecdsa.rs#L95C20-L95C27

Could you please provide detailed information or examples on how the "data" variable in this code snippet is serialized and deserialized?

Your insights will be extremely helpful. Thank you in advance for your assistance.

**Comment by Nashtare** [comment]
Hi!

In general, you'd serialize `CircuitData` upon generation as:

```rust
let data = builder.build::<C>();

let gate_serializer = DefaultGateSerializer;
let generator_serializer = DefaultGeneratorSerializer {
    _phantom: PhantomData,
};
let data_bytes = data.to_bytes(&gate_serializer, &generator_serializer)?;
let data2 = CircuitData::from_bytes(&bytes, &gate_serializer, &generator_serializer)?;

assert_eq!(data, data2);
```

The two special serializers are necessary to be able to generate the serialized bytes:
- `gate_serializer` to encode gates information, necessary for `CommonCircuitData`
- `generator_serializer` to encode generators information, necessary for `ProverCircuitData`.

`plonky2` crate provides default serializers for both that support all gates / generators defined within the crate. For applications that need to define, say a custom gate, they'll need to construct their own serializer that is aware of all gates used for a given circuit. An example of such is given in the [square root integration test](https://github.com/0xPolygonZero/plonky2/blob/main/plonky2/examples/square_root.rs).

**Comment by Nashtare** [comment]
Note however that the `plonky-ecdsa` crate is partly unmaintained, and `plonky2-u32` (one of its dependencies) is obsolete and unmaintained, which would require you to do several changes before having it running in the test you linked.
Let me know if you have any question!

**Comment by kiwi202202** [comment]
I have defined a `generator_serializer` as shown below. However, I realized that in the ECDSA circuit, some NonNative operations are performed on `Secp256K1Base`, while others are on `Secp256K1Scalar`. How should I handle this situation? For instance, `split_nonnative_to_4_bit_limbs` depends on `Secp256K1Scalar`, whereas `builder.constant_affine_point` relies on `Secp256K1Base`. Here's how I've defined the serializer:

```rust
    let generator_serializer = CustomGeneratorSerializer {
        _phantom: PhantomData::<C>,
        _phantom2: PhantomData::<Secp256K1Base>,
        _phantom3: PhantomData::<Secp256K1Scalar>,
    };

pub struct CustomGeneratorSerializer<
    C: GenericConfig<D>,
    FF1: PrimeField,
    FF2: PrimeField,
    const D: usize,
> {
    pub _phantom: PhantomData<C>,
    pub _phantom2: PhantomData<FF1>,
    pub _phantom3: PhantomData<FF2>,
}

impl<F, FF1, FF2, C, const D: usize> WitnessGeneratorSerializer<F, D>
    for CustomGeneratorSerializer<C, FF1, FF2, D>
where
    F: RichField + Extendable<D>,
    C: GenericConfig<D, F = F> + 'static,
    C::Hasher: AlgebraicHasher<F>,
    FF1: PrimeField,
    FF2: PrimeField,
{
    impl_generator_serializer! {
        // CustomGeneratorSerializer,
        DummyProofGenerator<F, C, D>,
        ArithmeticBaseGenerator<F, D>,
        ConstantGenerator<F>,
        PoseidonGenerator<F, D>,
        PoseidonMdsGenerator<D>,
        Poseidon2Generator<F, D>,
        RandomValueGenerator,
        BaseSumGenerator<4>,
        NonNativeMultiplicationGenerator<F, D, FF2>,
        NonNativeAdditionGenerator<F, D, FF2>,
        NonNativeInverseGenerator<F, D, FF2>,
        NonNativeSubtractionGenerator<F, D, FF2>,
        GLVDecompositionGenerator<F, D>,
        U32RangeCheckGenerator<F, D>,
        EqualityGenerator,
        U32ArithmeticGenerator<F, D>,
        U32AddManyGenerator<F, D>,
        ComparisonGenerator<F,D>,
        BaseSplitGenerator<2>,
        RandomAccessGenerator<F, D>,
        U32SubtractionGenerator<F, D>
    }
}

```

**Comment by Nashtare** [comment]
@kiwi202202 Do you have a repository I can look at? What exactly is your problem here?

**Comment by kiwi202202** [comment]
Here is the repo: https://github.com/ZeroKPunk/Plonky2-lib.git

I am encountering an issue where I cannot use the deserialized data (`data_from_bytes`) for proving in src/ecdsa/gadgets/ecdsa.rs. I suspect this might be related to how `PrimeField` is configured. Additionally, I identified and corrected a minor issue in this repository:

The order of serialization and deserialization in `NonNativeInverseGenerator` does not align. The issue can be resolved by adjusting the order in serialization as follows:

```rust
dst.write_biguint_target(self.x.value.clone())?;
dst.write_biguint_target(self.inv.clone())?;
dst.write_biguint_target(self.div.clone())?;
```

This change ensures that the serialization and deserialization sequences match correctly.

**Comment by Nashtare** [comment]
I can't compile the link you shared, it's containing references to `poseidon2` within `plonky2` which is not included in the crate. Can you provide additional inputs as to how you ran it / tested it?

As for your comment on order of deserialization, indeed you need to process elements in the same order as they were serialized, otherwise you'd be looking at the wrong byte section for a given object.

**Comment by kiwi202202** [comment]
Sorry for not being clear earlier. You can use this `plonky2` library from this repository: [https://github.com/ZeroKPunk/plonky2](https://github.com/ZeroKPunk/plonky2). Then, you should comment out the Poseidon2 part. After doing this, it should compile and run successfully. Here is the command I used to run it:

```bash
RUSTFLAGS=-Ctarget-cpu=native cargo test --package Plonky2-lib --release --lib -- ecdsa::gadgets::ecdsa::tests::test_batch_ecdsa_circuit_narrow --exact --nocapture --ignored
```
You may change `batch_num` to 1 for easier testing.

**Comment by kiwi202202** [comment]
I've identified a serialization issue in the ECDSA verify message circuit, specifically in the following invoked function:

```rust
let point1 = fixed_base_curve_mul_circuit(builder, Secp256K1::GENERATOR_AFFINE, &u1);
```
Within this function, there is a line of code:

```rust
let limbs = builder.split_nonnative_to_4_bit_limbs(scalar);
```
This line seems to be causing an error in the zkp verification:
```
thread 'ecdsa::gadgets::ecdsa::tests::test_batch_ecdsa_circuit_narrow' panicked at src/ecdsa/gadgets/ecdsa.rs:407:24:
called `Result::unwrap()` on an `Err` value: Condition failed: `vanishing_polys_zeta[i] == z_h_zeta * reduce_with_powers(chunk, zeta_pow_deg)`
```
 Is there any way to address this problem?
